
export const banderas = [
    {
        name:'United Arab Emirates',
        code:'ae',
        flag:'https://restcountries.eu/data/are.svg',
        nativeName:"دولة الإمارات العربية المتحدة"
    },
    {
        name:'Argentina',
        code:'ar',
        flag:'https://restcountries.eu/data/arg.svg',
        nativeName:"Argentina"
    },
    {
        name:'Austria',
        code:'at',
        flag:'https://restcountries.eu/data/aut.svg',
        nativeName:"Österreich"
    },
    {
        name:'Australia',
        code:'au',
        flag:'https://restcountries.eu/data/aus.svg',
        nativeName:"Australia"
    },
    {
        name:'Belgium',
        code:'be',
        flag:'https://restcountries.eu/data/bel.svg',
        nativeName:"België"
    },
    {
        name:'Bulgaria',
        code:'bg',
        flag:'https://restcountries.eu/data/bgr.svg',
        nativeName:"България"
    },
    {
        name:'Brazil',
        code:'br',
        flag:'https://restcountries.eu/data/bra.svg',
        nativeName:"Brasil"
    },
    {
        name:'Canada',
        code:'ca',
        flag:'https://restcountries.eu/data/can.svg',
        nativeName:"Canada"
    },
    {
        name:'Switzerland',
        code:'ch',
        flag:'https://restcountries.eu/data/che.svg',
        nativeName:"Schweiz"
    },
    {
        name:'China',
        code:'cn',
        flag:'https://restcountries.eu/data/chn.svg',
        nativeName:"中国"
    },
    {
        name:'Colombia',
        code:'co',
        flag:'https://restcountries.eu/data/col.svg',
        nativeName:"Colombia"
    },
    {
        name:'Cuba',
        code:'cu',
        flag:'https://restcountries.eu/data/cub.svg',
        nativeName:"Cuba"
    },
    {
        name:'Czech Republic',
        code:'cz',
        flag:'https://restcountries.eu/data/cze.svg',
        nativeName:"Česká republika"
    },
    {
        name:'Germany',
        code:'de',
        flag:'https://restcountries.eu/data/deu.svg',
        nativeName:"Deutschland"
    },
    {
        name:'France',
        code:'fr',
        flag:'https://restcountries.eu/data/fra.svg',
        nativeName:"France"
    },
    {
        name:'United Kingdom of Great Britain and Northern Ireland',
        code:'gb',
        flag:'https://restcountries.eu/data/gbr.svg',
        nativeName:"United Kingdom"
    },
    {
        name:'Greece',
        code:'gr',
        flag:'https://restcountries.eu/data/grc.svg',
        nativeName:"Ελλάδα"
    },
    {
        name:'Hong Kong',
        code:'hk',
        flag:'https://restcountries.eu/data/hkg.svg',
        nativeName:"香港"
    },
]

